In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e7/sample_submission.csv
/kaggle/input/playground-series-s4e7/train.csv
/kaggle/input/playground-series-s4e7/test.csv


In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(color_codes=True)

# Importing Data

In [3]:
data_train=pd.read_csv('/kaggle/input/playground-series-s4e7/train.csv')
data_train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   0    Male   21                1         35.0                   0   
1   1    Male   43                1         28.0                   0   
2   2  Female   25                1         14.0                   1   
3   3  Female   35                1          1.0                   0   
4   4  Female   36                1         15.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes         65101.0                 124.0      187   
1   > 2 Years            Yes         58911.0                  26.0      288   
2    < 1 Year             No         38043.0                 152.0      254   
3    1-2 Year            Yes          2630.0                 156.0       76   
4    1-2 Year             No         31951.0                 152.0      294   

   Response  
0         0  
1         1  
2         0  
3         0  
4         0

In [4]:
data_test=pd.read_csv('/kaggle/input/playground-series-s4e7/test.csv')
data_test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  11504798  Female   20                1         47.0                   0   
1  11504799    Male   47                1         28.0                   0   
2  11504800    Male   47                1         43.0                   0   
3  11504801  Female   22                1         47.0                   1   
4  11504802    Male   51                1         19.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No          2630.0                 160.0      228  
1    1-2 Year            Yes         37483.0                 124.0      123  
2    1-2 Year            Yes          2630.0                  26.0      271  
3    < 1 Year             No         24502.0                 152.0      115  
4    1-2 Year             No         34115.0                 124.0      148

# EDA

In [5]:
data_train.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [6]:
#sns.barplot(data=data_train, x='Response',y='Vintage')

In [7]:
# sns.barplot(data=data_train, x='Response',y='Policy_Sales_Channel')

In [8]:
# sns.barplot(data=data_train, x='Response',y='Annual_Premium')

# Data Preprocessing

In [9]:
data_train.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [10]:
# columns in the DataFrame that have data types classified as 'object'. 
#In pandas, the 'object' data type is typically used for text or categorical data.
data_train.select_dtypes(include='object').nunique()

Gender            2
Vehicle_Age       3
Vehicle_Damage    2
dtype: int64

In [11]:
data_train.nunique() # tells all the unique value a column holds

id                      11504798
Gender                         2
Age                           66
Driving_License                2
Region_Code                   54
Previously_Insured             2
Vehicle_Age                    3
Vehicle_Damage                 2
Annual_Premium             51728
Policy_Sales_Channel         152
Vintage                      290
Response                       2
dtype: int64

In [12]:
# removing id column
data_train.drop('id', axis=1,inplace=True)
data_train.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured Vehicle_Age  \
0    Male   21                1         35.0                   0    1-2 Year   
1    Male   43                1         28.0                   0   > 2 Years   
2  Female   25                1         14.0                   1    < 1 Year   
3  Female   35                1          1.0                   0    1-2 Year   
4  Female   36                1         15.0                   1    1-2 Year   

  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  
0            Yes         65101.0                 124.0      187         0  
1            Yes         58911.0                  26.0      288         1  
2             No         38043.0                 152.0      254         0  
3            Yes          2630.0                 156.0       76         0  
4             No         31951.0                 152.0      294         0

In [13]:
data_train['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
data_train['Vehicle_Age'].unique()

array(['1-2 Year', '> 2 Years', '< 1 Year'], dtype=object)

In [15]:
data_train['Vehicle_Damage'].unique()

array(['Yes', 'No'], dtype=object)

In [16]:
# Transforming Object Categorical data into int using label Encoder

In [17]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [18]:
data_train['Gender']=label_encoder.fit_transform(data_train['Gender'])
data_train['Gender'].unique()

array([1, 0])

In [19]:
data_train['Vehicle_Age']=label_encoder.fit_transform(data_train['Vehicle_Age'])
data_train['Vehicle_Age'].unique()

array([0, 2, 1])

In [20]:
data_train['Vehicle_Damage']=label_encoder.fit_transform(data_train['Vehicle_Damage'])
data_train['Vehicle_Damage'].unique()

array([1, 0])

In [21]:
data_train.head()

Gender  Age  Driving_License  Region_Code  Previously_Insured  Vehicle_Age  \
0       1   21                1         35.0                   0            0   
1       1   43                1         28.0                   0            2   
2       0   25                1         14.0                   1            1   
3       0   35                1          1.0                   0            0   
4       0   36                1         15.0                   1            0   

   Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  Response  
0               1         65101.0                 124.0      187         0  
1               1         58911.0                  26.0      288         1  
2               0         38043.0                 152.0      254         0  
3               1          2630.0                 156.0       76         0  
4               0         31951.0                 152.0      294         0

In [22]:
data_train.dtypes

Gender                    int64
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age               int64
Vehicle_Damage            int64
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
Response                  int64
dtype: object

# Check if Response colum is balance or not

In [23]:
# sns.countplot(x=data_train['Response'])

# plt.figure(figsize=(5, 5))

In [24]:
data_train['Response'].value_counts()

Response
0    10089739
1     1415059
Name: count, dtype: int64

In [25]:
# seperating 1 and 0 in different columns
df_major= data_train[(data_train['Response']==0)]
df_minor= data_train[(data_train['Response']==1)]

In [26]:
# up sampling minority '1' column equal to majority '0'
# Response
# 0    10089739
# 1     1415059

In [27]:
from sklearn.utils import resample

df_minor_upsample=resample(df_minor, replace=True, n_samples=10089739, random_state=0)

df_upsampled=pd.concat([df_minor_upsample, df_major])

In [28]:
df_upsampled

Gender  Age  Driving_License  Region_Code  Previously_Insured  \
2491338        0   38                1         46.0                   0   
962117         1   48                1         28.0                   0   
7831406        0   20                1         50.0                   0   
1242312        1   58                1          8.0                   0   
2929171        1   50                1         18.0                   0   
...          ...  ...              ...          ...                 ...   
11504791       0   31                1         32.0                   1   
11504792       1   34                1         28.0                   1   
11504793       1   48                1          6.0                   0   
11504795       0   29                1         32.0                   1   
11504797       1   25                1         28.0                   1   

          Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  \
2491338             0               1         29679.0                  26.0   
962117              0               1         49092.0                 124.0   
7831406             1               1         34187.0                 160.0   
1242312             0               1          2630.0                  30.0   
2929171             0               1         37190.0                  26.0   
...               ...             ...             ...                   ...   
11504791            1               0          2630.0                 152.0   
11504792            0               0         29974.0                 154.0   
11504793            0               1         27412.0                  26.0   
11504795            1               0          2630.0                 152.0   
11504797            1               0         32855.0                 152.0   

          Vintage  Response  
2491338        11         1  
962117        182         1  
7831406        92         1  
1242312       212         1  
2929171       208         1  
...           ...       ...  
11504791      204         0  
11504792      201         0  
11504793      218         0  
11504795      189         0  
11504797      189         0  

[20179478 rows x 11 columns]

In [29]:
# sns.countplot(x=df_upsampled['Response'])

# plt.figure(figsize=(5, 5))

# Checking Outliers

In [30]:
# sns.boxplot(x=df_upsampled['Age'])

In [31]:
# sns.boxplot(x=df_upsampled['Annual_Premium'])

In [32]:
# sns.boxplot(x=df_upsampled['Policy_Sales_Channel'])

In [33]:
 # sns.boxplot(x=df_upsampled['Vintage'])

In [34]:
df_upsampled.shape

(20179478, 11)

In [35]:
# Remove The outliers using z-Score Method

In [36]:
import scipy.stats as stats
z=np.abs(stats.zscore(df_upsampled))
data_clean = df_upsampled[(z<3).all(axis=1)]

data_clean.shape

(20125233, 11)

# Heatmap Corellation

In [37]:
# sns.heatmap(data_clean, annot=True, fmt='.2g', cmap='coolwarm')

In [38]:
# removing driving Licence because it doesnt have any corelation with response
data_clean.drop('Driving_License', axis=1, inplace= True)

/tmp/ipykernel_18/3443047114.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_clean.drop('Driving_License', axis=1, inplace= True)


In [39]:
data_clean.head()

Gender  Age  Region_Code  Previously_Insured  Vehicle_Age  \
2491338       0   38         46.0                   0            0   
962117        1   48         28.0                   0            0   
7831406       0   20         50.0                   0            1   
1242312       1   58          8.0                   0            0   
2929171       1   50         18.0                   0            0   

         Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
2491338               1         29679.0                  26.0       11   
962117                1         49092.0                 124.0      182   
7831406               1         34187.0                 160.0       92   
1242312               1          2630.0                  30.0      212   
2929171               1         37190.0                  26.0      208   

         Response  
2491338         1  
962117          1  
7831406         1  
1242312         1  
2929171         1

# Preparing Test Data

In [40]:
data_test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  11504798  Female   20                1         47.0                   0   
1  11504799    Male   47                1         28.0                   0   
2  11504800    Male   47                1         43.0                   0   
3  11504801  Female   22                1         47.0                   1   
4  11504802    Male   51                1         19.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No          2630.0                 160.0      228  
1    1-2 Year            Yes         37483.0                 124.0      123  
2    1-2 Year            Yes          2630.0                  26.0      271  
3    < 1 Year             No         24502.0                 152.0      115  
4    1-2 Year             No         34115.0                 124.0      148

In [41]:
data_test.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
dtype: int64

In [42]:
x_test= data_test.drop(['id','Driving_License'], axis=1)
x_test.head()

Gender  Age  Region_Code  Previously_Insured Vehicle_Age Vehicle_Damage  \
0  Female   20         47.0                   0    < 1 Year             No   
1    Male   47         28.0                   0    1-2 Year            Yes   
2    Male   47         43.0                   0    1-2 Year            Yes   
3  Female   22         47.0                   1    < 1 Year             No   
4    Male   51         19.0                   0    1-2 Year             No   

   Annual_Premium  Policy_Sales_Channel  Vintage  
0          2630.0                 160.0      228  
1         37483.0                 124.0      123  
2          2630.0                  26.0      271  
3         24502.0                 152.0      115  
4         34115.0                 124.0      148

In [43]:
x_test['Gender']=label_encoder.fit_transform(x_test['Gender'])
x_test['Gender'].unique()

x_test['Vehicle_Age']=label_encoder.fit_transform(x_test['Vehicle_Age'])
x_test['Vehicle_Age'].unique()

x_test['Vehicle_Damage']=label_encoder.fit_transform(x_test['Vehicle_Damage'])
x_test['Gender'].unique()

array([0, 1])

In [44]:
x_test.shape

(7669866, 9)

In [45]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7669866 entries, 0 to 7669865
Data columns (total 9 columns):
 #   Column                Dtype  
---  ------                -----  
 0   Gender                int64  
 1   Age                   int64  
 2   Region_Code           float64
 3   Previously_Insured    int64  
 4   Vehicle_Age           int64  
 5   Vehicle_Damage        int64  
 6   Annual_Premium        float64
 7   Policy_Sales_Channel  float64
 8   Vintage               int64  
dtypes: float64(3), int64(6)
memory usage: 526.6 MB


# Applying ML Model

In [46]:
X = data_clean.drop('Response', axis=1)
Y= data_clean['Response']

In [47]:
from sklearn.metrics import accuracy_score

# Desicion Tree Classifier

In [48]:
from sklearn.tree import DecisionTreeClassifier

DTC= DecisionTreeClassifier(random_state=0)
DTC.fit(X,Y)

DecisionTreeClassifier(random_state=0)

In [49]:
y_pred=DTC.predict(x_test)


In [50]:
submission = pd.DataFrame({'id':data_test['id'], 'Response':y_pred})
submission = submission[['id','Response']]
submission.head()

id  Response
0  11504798         0
1  11504799         0
2  11504800         0
3  11504801         0
4  11504802         0

In [51]:
submission.to_csv('/kaggle/working/submission.csv', index=False)